# Generated by Django 4.0.4 on 2022-05-21 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_instructor_course_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
    ]
