# Generated by Django 4.0.4 on 2022-05-18 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_course_students'),
        ('accounts', '0003_alter_accounts_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='course',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='course.course'),
        ),
    ]
