# Generated by Django 4.0.4 on 2022-05-20 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_course_students'),
        ('accounts', '0005_alter_accounts_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='instructor_course',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to='course.course'),
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='course',
        ),
        migrations.AddField(
            model_name='accounts',
            name='course',
            field=models.ManyToManyField(null=True, related_name='students', to='course.course'),
        ),
    ]
