# Generated by Django 4.0.4 on 2022-05-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_remove_course_students'),
        ('accounts', '0007_remove_accounts_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='courses',
            field=models.ManyToManyField(null=True, related_name='students', to='course.course'),
        ),
    ]
