# Generated by Django 4.0.4 on 2022-05-21 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_accounts_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='courses',
        ),
    ]
