# Generated by Django 4.0.4 on 2022-05-07 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='accounts',
            new_name='users',
        ),
    ]
